navigation.icon: i-lucide-book-open
title: 'Documentation'
items:
  - title: 'Getting Started'
    to: '/docs/getting-started'
  - title: 'ACT Handbook'
    to: '/docs/act-handbook'
    icon: 'heroicons:book-open'